site_name: airdb
site_description:  https://airdb.io
site_author: YiNo Team

repo_url: https://github.com/airdb
edit_uri: https://github.com/airdb/index

copyright: Copyright &copy; 2014 <a href="https://github.com/airdb">Dean</a>, Maintained by the <a href="https://github.com/orgs/airdb/people">YiNo Team</a>.

theme: Flatly

pages:
- 概览: index.md
- 技术公益: lovelytech.md
- 守护者: Maintainers.md
- 维护项目: 
        - '宝贝回家': project/bbhj.airdb.io.md
#- 持续集成: ci.md
#- 持续部署: cd.md
#- AWS: aws/awscli.md
#- 机器学习: AIAlgorithm.md
#- 职业生涯: career.md
- SRE文化: sre.md
- AIFM的想法: aifm.md
- MyCql的学习历程: Mycql/StudyDay1.md
#- 关于求职: jobs/salary.md
- 关于真实: dean/sincere.md
- 文档贡献: 03_how_to_github_pull_request.md
- 文档排版: 04_chinese_copywrite_guidelines.md
